name: a2tg
channels:
  - conda-forge
dependencies:
  - python=3.12
  - pip
  - setuptools=69.5.1
  - pip:
      - ninja
      - --extra-index-url https://download.pytorch.org/whl/cu128
      - torch==2.7.1
      - torchvision==0.22.1
      - torchaudio==2.7.1
